export const HTTP_REQUEST_FLOW_EVENT_TYPES = {
  DNS_START: 'DNS_START',
  DNS_RESOLVER_QUERY: 'DNS_RESOLVER_QUERY',
  DNS_AUTHORITATIVE_RESPONSE: 'DNS_AUTHORITATIVE_RESPONSE',
  DNS_END: 'DNS_END',
  TCP_SYN: 'TCP_SYN',
  TCP_SYN_ACK: 'TCP_SYN_ACK',
  TCP_ACK: 'TCP_ACK',
  TLS_CLIENT_HELLO: 'TLS_CLIENT_HELLO',
  TLS_SERVER_HELLO: 'TLS_SERVER_HELLO',
  HTTP_REQUEST_SENT: 'HTTP_REQUEST_SENT',
  REQUEST_RECEIVED: 'REQUEST_RECEIVED',
  PROXY_FORWARD: 'PROXY_FORWARD',
  LOAD_BALANCER_ROUTE: 'LOAD_BALANCER_ROUTE',
  GATEWAY_DISPATCH: 'GATEWAY_DISPATCH',
  MICROSERVICE_DISPATCH: 'MICROSERVICE_DISPATCH',
  BUSINESS_LOGIC_EXECUTE: 'BUSINESS_LOGIC_EXECUTE',
  DATABASE_QUERY: 'DATABASE_QUERY',
  WAL_WRITE: 'WAL_WRITE',
  DATABASE_RESPONSE: 'DATABASE_RESPONSE',
  HTTP_RESPONSE_SENT: 'HTTP_RESPONSE_SENT',
  RESPONSE_RECEIVED: 'RESPONSE_RECEIVED',
  FINISHED: 'FINISHED',
} as const;

export type HttpRequestFlowEventType =
  (typeof HTTP_REQUEST_FLOW_EVENT_TYPES)[keyof typeof HTTP_REQUEST_FLOW_EVENT_TYPES];
