import { ExperienceManifest } from '../../../engine/assets/contracts/experience-manifest.types';
import {
  DEFAULT_HTTP_REQUEST_FLOW_3D_SCENE,
  HTTP_REQUEST_FLOW_SCENE_DATA,
} from './http-request-flow.scene';

export const HTTP_REQUEST_FLOW_MANIFEST: ExperienceManifest = {
  $schema: 'https://casevisuallab.dev/schemas/v2/experience-manifest.json',
  schemaVersion: '2.0.0',
  manifestVersion: '1.0.0',
  contentVersion: '1.0.0',
  metadata: {
    id: 'http-request-flow',
    slug: 'http-request-flow',
    title: 'HTTP Request Flow MVP',
    subtitle: 'End-to-End Lifecycle: Browser, DNS, TCP, TLS, Ingress, Microservice, DB & WAL',
    description:
      'Reference architectural experience validating the unified CASE Visual Lab execution engine.',
    author: {
      name: 'CASE Visual Lab Engineering',
    },
    organization: 'CASE Visual Lab',
    difficulty: 'Intermediate',
    estimatedMinutes: 5,
    tags: ['networking', 'http', 'dns', 'tcp', 'database', 'architecture'],
    category: 'Networking',
    version: '1.0.0',
  },
  profile: {
    type: 'simulation',
    policy: {
      autoPlay: false,
      loop: false,
    },
  },
  simulation: {
    provider: 'http-request-flow-simulation-provider',
    scenario: 'http-request-flow-order-creation',
    initialVariables: {
      method: 'POST',
      url: 'https://api.example.com/api/v1/orders',
      domain: 'api.example.com',
      path: '/api/v1/orders',
      resolvedIp: '198.51.100.1',
      status: 200,
    },
  },
  timeline: {
    durationMs: 12000,
    loop: false,
    tracks: [
      {
        id: 'track_camera',
        name: 'Camera Movement',
        type: 'CAMERA',
        frames: [
          {
            id: 'cam_f_0',
            time: 0,
            duration: 400,
            commands: [
              {
                id: 'cmd_cam_0',
                type: 'FOCUS_CAMERA',
                targetId: 'node_browser',
                payload: { target: 'node_browser', zoom: 1.0 },
                durationMs: 400,
                easing: 'ease-out',
                priority: 'NORMAL',
              },
            ],
            metadata: { stage: 'DNS_START', track: 'track_camera' },
          },
          {
            id: 'cam_f_1',
            time: 500,
            duration: 400,
            commands: [
              {
                id: 'cmd_cam_1',
                type: 'FOCUS_CAMERA',
                targetId: 'node_dns_resolver',
                payload: { target: 'node_dns_resolver', zoom: 1.1 },
                durationMs: 400,
                easing: 'ease-out',
                priority: 'NORMAL',
              },
            ],
            metadata: { stage: 'DNS_RESOLVE', track: 'track_camera' },
          },
          {
            id: 'cam_f_2',
            time: 2000,
            duration: 400,
            commands: [
              {
                id: 'cmd_cam_2',
                type: 'FOCUS_CAMERA',
                targetId: 'node_reverse_proxy',
                payload: { target: 'node_reverse_proxy', zoom: 1.05 },
                durationMs: 400,
                easing: 'ease-out',
                priority: 'NORMAL',
              },
            ],
            metadata: { stage: 'TCP_SYN', track: 'track_camera' },
          },
          {
            id: 'cam_f_3',
            time: 4500,
            duration: 400,
            commands: [
              {
                id: 'cmd_cam_3',
                type: 'FOCUS_CAMERA',
                targetId: 'node_api_gateway',
                payload: { target: 'node_api_gateway', zoom: 1.05 },
                durationMs: 400,
                easing: 'ease-out',
                priority: 'NORMAL',
              },
            ],
            metadata: { stage: 'GATEWAY_DISPATCH', track: 'track_camera' },
          },
          {
            id: 'cam_f_4',
            time: 6600,
            duration: 400,
            commands: [
              {
                id: 'cmd_cam_4',
                type: 'FOCUS_CAMERA',
                targetId: 'node_microservice',
                payload: { target: 'node_microservice', zoom: 1.1 },
                durationMs: 400,
                easing: 'ease-out',
                priority: 'NORMAL',
              },
            ],
            metadata: { stage: 'MICROSERVICE_DISPATCH', track: 'track_camera' },
          },
          {
            id: 'cam_f_5',
            time: 7800,
            duration: 400,
            commands: [
              {
                id: 'cmd_cam_5',
                type: 'FOCUS_CAMERA',
                targetId: 'node_database',
                payload: { target: 'node_database', zoom: 1.1 },
                durationMs: 400,
                easing: 'ease-out',
                priority: 'NORMAL',
              },
            ],
            metadata: { stage: 'DATABASE_QUERY', track: 'track_camera' },
          },
          {
            id: 'cam_f_6',
            time: 9500,
            duration: 400,
            commands: [
              {
                id: 'cmd_cam_6',
                type: 'FOCUS_CAMERA',
                targetId: 'node_browser',
                payload: { target: 'node_browser', zoom: 1.0 },
                durationMs: 400,
                easing: 'ease-out',
                priority: 'NORMAL',
              },
            ],
            metadata: { stage: 'RESPONSE_RECEIVED', track: 'track_camera' },
          },
        ],
      },
      {
        id: 'track_packets',
        name: 'Packets & Three.js Overlay',
        type: 'VISUAL',
        frames: [
          {
            id: 'pkt_f_0',
            time: 0,
            duration: 500,
            commands: [
              {
                id: 'cmd_p_dns_1',
                type: 'SPAWN_PARTICLE',
                targetId: 'node_browser',
                payload: {
                  particleId: 'p_dns_1',
                  sourceEntityId: 'node_browser',
                  targetEntityId: 'node_dns_resolver',
                },
                durationMs: 0,
                easing: 'linear',
                priority: 'NORMAL',
              },
              {
                id: 'cmd_p_dns_1_mv',
                type: 'MOVE_PARTICLE',
                targetId: 'p_dns_1',
                payload: { destinationEntityId: 'node_dns_resolver' },
                durationMs: 500,
                easing: 'ease-out',
                priority: 'NORMAL',
              },
            ],
            metadata: { event: 'DNS_START', track: 'track_packets' },
          },
          {
            id: 'pkt_f_1',
            time: 2000,
            duration: 500,
            commands: [
              {
                id: 'cmd_p_tcp_syn',
                type: 'SPAWN_PARTICLE',
                targetId: 'node_browser',
                payload: {
                  particleId: 'p_tcp_syn',
                  sourceEntityId: 'node_browser',
                  targetEntityId: 'node_reverse_proxy',
                },
                durationMs: 0,
                easing: 'linear',
                priority: 'NORMAL',
              },
              {
                id: 'cmd_p_tcp_syn_mv',
                type: 'MOVE_PARTICLE',
                targetId: 'p_tcp_syn',
                payload: { destinationEntityId: 'node_reverse_proxy' },
                durationMs: 500,
                easing: 'ease-out',
                priority: 'NORMAL',
              },
            ],
            metadata: { event: 'TCP_SYN', track: 'track_packets' },
          },
          {
            id: 'pkt_f_2',
            time: 4500,
            duration: 600,
            commands: [
              {
                id: 'cmd_p_http_req',
                type: 'SPAWN_PARTICLE',
                targetId: 'node_browser',
                payload: {
                  particleId: 'p_http_req',
                  sourceEntityId: 'node_browser',
                  targetEntityId: 'node_reverse_proxy',
                },
                durationMs: 0,
                easing: 'linear',
                priority: 'NORMAL',
              },
              {
                id: 'cmd_p_http_req_mv',
                type: 'MOVE_PARTICLE',
                targetId: 'p_http_req',
                payload: { destinationEntityId: 'node_reverse_proxy' },
                durationMs: 600,
                easing: 'ease-out',
                priority: 'NORMAL',
              },
            ],
            metadata: { event: 'HTTP_REQUEST_SENT', track: 'track_packets' },
          },
          {
            id: 'pkt_f_3',
            time: 7800,
            duration: 600,
            commands: [
              {
                id: 'cmd_p_db_qry',
                type: 'SPAWN_PARTICLE',
                targetId: 'node_business_layer',
                payload: {
                  particleId: 'p_db_qry',
                  sourceEntityId: 'node_business_layer',
                  targetEntityId: 'node_database',
                },
                durationMs: 0,
                easing: 'linear',
                priority: 'NORMAL',
              },
              {
                id: 'cmd_p_db_qry_mv',
                type: 'MOVE_PARTICLE',
                targetId: 'p_db_qry',
                payload: { destinationEntityId: 'node_database' },
                durationMs: 600,
                easing: 'ease-out',
                priority: 'NORMAL',
              },
            ],
            metadata: { event: 'DATABASE_QUERY', track: 'track_packets' },
          },
          {
            id: 'pkt_f_4',
            time: 9500,
            duration: 700,
            commands: [
              {
                id: 'cmd_p_http_resp',
                type: 'SPAWN_PARTICLE',
                targetId: 'node_reverse_proxy',
                payload: {
                  particleId: 'p_http_resp',
                  sourceEntityId: 'node_reverse_proxy',
                  targetEntityId: 'node_browser',
                },
                durationMs: 0,
                easing: 'linear',
                priority: 'NORMAL',
              },
              {
                id: 'cmd_p_http_resp_mv',
                type: 'MOVE_PARTICLE',
                targetId: 'p_http_resp',
                payload: { destinationEntityId: 'node_browser' },
                durationMs: 700,
                easing: 'ease-out',
                priority: 'NORMAL',
              },
            ],
            metadata: { event: 'HTTP_RESPONSE_SENT', track: 'track_packets' },
          },
        ],
      },
      {
        id: 'track_http',
        name: 'HTTP & Transport State',
        type: 'CUSTOM',
        frames: [
          {
            id: 'http_f_0',
            time: 0,
            duration: 2000,
            commands: [
              {
                id: 'cmd_bdg_dns',
                type: 'UPDATE_BADGE',
                targetId: 'node_dns_resolver',
                payload: { text: 'DNS Resolving', intent: 'info' },
                durationMs: 300,
                easing: 'linear',
                priority: 'NORMAL',
              },
            ],
            metadata: { stage: 'DNS', track: 'track_http' },
          },
          {
            id: 'http_f_1',
            time: 2000,
            duration: 1500,
            commands: [
              {
                id: 'cmd_bdg_tcp',
                type: 'UPDATE_BADGE',
                targetId: 'node_reverse_proxy',
                payload: { text: 'TCP Handshake', intent: 'busy' },
                durationMs: 300,
                easing: 'linear',
                priority: 'NORMAL',
              },
            ],
            metadata: { stage: 'TCP', track: 'track_http' },
          },
          {
            id: 'http_f_2',
            time: 3500,
            duration: 1000,
            commands: [
              {
                id: 'cmd_bdg_tls',
                type: 'UPDATE_BADGE',
                targetId: 'node_reverse_proxy',
                payload: { text: 'TLS 1.3 OK', intent: 'success' },
                durationMs: 300,
                easing: 'linear',
                priority: 'NORMAL',
              },
            ],
            metadata: { stage: 'TLS', track: 'track_http' },
          },
          {
            id: 'http_f_3',
            time: 4500,
            duration: 2100,
            commands: [
              {
                id: 'cmd_bdg_http',
                type: 'UPDATE_BADGE',
                targetId: 'node_api_gateway',
                payload: { text: 'POST /orders', intent: 'transmitting' },
                durationMs: 300,
                easing: 'linear',
                priority: 'NORMAL',
              },
            ],
            metadata: { stage: 'HTTP_DISPATCH', track: 'track_http' },
          },
          {
            id: 'http_f_4',
            time: 9500,
            duration: 1500,
            commands: [
              {
                id: 'cmd_bdg_resp',
                type: 'UPDATE_BADGE',
                targetId: 'node_browser',
                payload: { text: '200 OK', intent: 'success' },
                durationMs: 300,
                easing: 'linear',
                priority: 'NORMAL',
              },
            ],
            metadata: { stage: 'HTTP_RESPONSE', track: 'track_http' },
          },
        ],
      },
      {
        id: 'track_database',
        name: 'Database & WAL Durability',
        type: 'CUSTOM',
        frames: [
          {
            id: 'db_f_0',
            time: 7800,
            duration: 600,
            commands: [
              {
                id: 'cmd_bdg_db_qry',
                type: 'UPDATE_BADGE',
                targetId: 'node_database',
                payload: { text: 'BEGIN TX', intent: 'busy' },
                durationMs: 300,
                easing: 'linear',
                priority: 'NORMAL',
              },
            ],
            metadata: { stage: 'DATABASE_QUERY', track: 'track_database' },
          },
          {
            id: 'db_f_1',
            time: 8400,
            duration: 500,
            commands: [
              {
                id: 'cmd_bdg_wal',
                type: 'UPDATE_BADGE',
                targetId: 'node_wal',
                payload: { text: 'WAL FSYNC', intent: 'warning' },
                durationMs: 300,
                easing: 'linear',
                priority: 'NORMAL',
              },
            ],
            metadata: { stage: 'WAL_WRITE', track: 'track_database' },
          },
          {
            id: 'db_f_2',
            time: 8900,
            duration: 600,
            commands: [
              {
                id: 'cmd_bdg_db_res',
                type: 'UPDATE_BADGE',
                targetId: 'node_database',
                payload: { text: 'COMMIT TX', intent: 'success' },
                durationMs: 300,
                easing: 'linear',
                priority: 'NORMAL',
              },
            ],
            metadata: { stage: 'DATABASE_RESPONSE', track: 'track_database' },
          },
        ],
      },
      {
        id: 'track_ui',
        name: 'Excalidraw Nodes & Highlights',
        type: 'VISUAL',
        frames: [
          {
            id: 'ui_f_0',
            time: 0,
            duration: 2000,
            commands: [
              {
                id: 'cmd_hl_dns',
                type: 'HIGHLIGHT_NODE',
                targetId: 'node_dns_resolver',
                payload: { intent: 'info', intensity: 0.8 },
                durationMs: 300,
                easing: 'linear',
                priority: 'NORMAL',
              },
            ],
            metadata: { target: 'node_dns_resolver', track: 'track_ui' },
          },
          {
            id: 'ui_f_1',
            time: 2000,
            duration: 2500,
            commands: [
              {
                id: 'cmd_hl_proxy',
                type: 'HIGHLIGHT_NODE',
                targetId: 'node_reverse_proxy',
                payload: { intent: 'busy', intensity: 0.8 },
                durationMs: 300,
                easing: 'linear',
                priority: 'NORMAL',
              },
            ],
            metadata: { target: 'node_reverse_proxy', track: 'track_ui' },
          },
          {
            id: 'ui_f_2',
            time: 4500,
            duration: 2100,
            commands: [
              {
                id: 'cmd_hl_gw',
                type: 'HIGHLIGHT_NODE',
                targetId: 'node_api_gateway',
                payload: { intent: 'success', intensity: 0.8 },
                durationMs: 300,
                easing: 'linear',
                priority: 'NORMAL',
              },
            ],
            metadata: { target: 'node_api_gateway', track: 'track_ui' },
          },
          {
            id: 'ui_f_3',
            time: 6600,
            duration: 1200,
            commands: [
              {
                id: 'cmd_hl_svc',
                type: 'HIGHLIGHT_NODE',
                targetId: 'node_microservice',
                payload: { intent: 'busy', intensity: 0.8 },
                durationMs: 300,
                easing: 'linear',
                priority: 'NORMAL',
              },
            ],
            metadata: { target: 'node_microservice', track: 'track_ui' },
          },
          {
            id: 'ui_f_4',
            time: 7800,
            duration: 1700,
            commands: [
              {
                id: 'cmd_hl_db',
                type: 'HIGHLIGHT_NODE',
                targetId: 'node_database',
                payload: { intent: 'success', intensity: 0.8 },
                durationMs: 300,
                easing: 'linear',
                priority: 'NORMAL',
              },
            ],
            metadata: { target: 'node_database', track: 'track_ui' },
          },
          {
            id: 'ui_f_5',
            time: 9500,
            duration: 1500,
            commands: [
              {
                id: 'cmd_hl_browser',
                type: 'HIGHLIGHT_NODE',
                targetId: 'node_browser',
                payload: { intent: 'success', intensity: 1.0 },
                durationMs: 300,
                easing: 'linear',
                priority: 'NORMAL',
              },
            ],
            metadata: { target: 'node_browser', track: 'track_ui' },
          },
        ],
      },
      {
        id: 'track_inspector',
        name: 'Telemetry & Metrics',
        type: 'CUSTOM',
        frames: [
          {
            id: 'insp_f_0',
            time: 0,
            duration: 2000,
            commands: [],
            metadata: {
              stage: 'DNS_START',
              activeNode: 'node_dns_resolver',
              latencyMs: 25,
              track: 'track_inspector',
            },
          },
          {
            id: 'insp_f_1',
            time: 2000,
            duration: 2500,
            commands: [],
            metadata: {
              stage: 'TCP_SYN',
              activeNode: 'node_reverse_proxy',
              latencyMs: 78,
              track: 'track_inspector',
            },
          },
          {
            id: 'insp_f_2',
            time: 4500,
            duration: 2100,
            commands: [],
            metadata: {
              stage: 'HTTP_REQUEST_SENT',
              activeNode: 'node_api_gateway',
              latencyMs: 112,
              track: 'track_inspector',
            },
          },
          {
            id: 'insp_f_3',
            time: 6600,
            duration: 1200,
            commands: [],
            metadata: {
              stage: 'MICROSERVICE_DISPATCH',
              activeNode: 'node_microservice',
              latencyMs: 145,
              track: 'track_inspector',
            },
          },
          {
            id: 'insp_f_4',
            time: 7800,
            duration: 1700,
            commands: [],
            metadata: {
              stage: 'DATABASE_QUERY',
              activeNode: 'node_database',
              latencyMs: 198,
              track: 'track_inspector',
            },
          },
          {
            id: 'insp_f_5',
            time: 9500,
            duration: 1500,
            commands: [],
            metadata: {
              stage: 'RESPONSE_RECEIVED',
              activeNode: 'node_browser',
              latencyMs: 220,
              track: 'track_inspector',
            },
          },
        ],
      },
    ],
    markers: [
      {
        id: 'marker_dns',
        name: 'DNS Resolution Hierarchy',
        time: 0,
        kind: 'CHECKPOINT',
      },
      {
        id: 'marker_tcp',
        name: 'TCP 3-Way Handshake',
        time: 2000,
        kind: 'CHECKPOINT',
      },
      {
        id: 'marker_tls',
        name: 'TLS 1.3 Cryptographic Handshake',
        time: 3500,
        kind: 'CHECKPOINT',
      },
      {
        id: 'marker_http',
        name: 'HTTP Request Transmission (POST /orders)',
        time: 4500,
        kind: 'CHECKPOINT',
      },
      {
        id: 'marker_ingress',
        name: 'Edge Ingress & Gateway Dispatch',
        time: 5100,
        kind: 'CHECKPOINT',
      },
      {
        id: 'marker_service',
        name: 'Microservice Domain Execution',
        time: 6600,
        kind: 'CHECKPOINT',
      },
      {
        id: 'marker_database',
        name: 'Database Transaction & WAL Durability',
        time: 7800,
        kind: 'CHECKPOINT',
      },
      {
        id: 'marker_response',
        name: 'HTTP 200 OK Response Flow',
        time: 9500,
        kind: 'CHECKPOINT',
      },
      {
        id: 'marker_finished',
        name: 'Request Lifecycle Completed',
        time: 11000,
        kind: 'CHECKPOINT',
      },
    ],
  },
  assets: {
    scenes: {
      main: HTTP_REQUEST_FLOW_SCENE_DATA,
      three: DEFAULT_HTTP_REQUEST_FLOW_3D_SCENE,
    },
  },
};
