import { CanvasSceneData } from '../../../domain/canvas/canvas-engine.interface';
import { ThreeSceneState } from '../../../infrastructure/renderers/three/contracts/particle-state.interface';

export const HTTP_REQUEST_FLOW_SCENE_DATA: CanvasSceneData = {
  elements: [
    {
      id: 'zone_client',
      type: 'rectangle',
      x: 50,
      y: 180,
      width: 250,
      height: 220,
      strokeColor: '#334155',
      backgroundColor: 'rgba(15, 23, 42, 0.4)',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text_zone_client',
      type: 'text',
      x: 60,
      y: 190,
      width: 150,
      height: 20,
      text: 'CLIENT TIER',
      fontSize: 12,
      fontFamily: 1,
      textAlign: 'left',
      verticalAlign: 'top',
      strokeColor: '#64748B',
      backgroundColor: 'transparent',
    },
    {
      id: 'zone_dns',
      type: 'rectangle',
      x: 330,
      y: 40,
      width: 920,
      height: 150,
      strokeColor: '#1E293B',
      backgroundColor: 'rgba(15, 23, 42, 0.3)',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text_zone_dns',
      type: 'text',
      x: 345,
      y: 50,
      width: 260,
      height: 20,
      text: 'DNS RESOLUTION HIERARCHY',
      fontSize: 12,
      fontFamily: 1,
      textAlign: 'left',
      verticalAlign: 'top',
      strokeColor: '#64748B',
      backgroundColor: 'transparent',
    },
    {
      id: 'zone_edge',
      type: 'rectangle',
      x: 330,
      y: 220,
      width: 920,
      height: 180,
      strokeColor: '#1E293B',
      backgroundColor: 'rgba(15, 23, 42, 0.3)',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text_zone_edge',
      type: 'text',
      x: 345,
      y: 230,
      width: 260,
      height: 20,
      text: 'EDGE & INGRESS TIER',
      fontSize: 12,
      fontFamily: 1,
      textAlign: 'left',
      verticalAlign: 'top',
      strokeColor: '#64748B',
      backgroundColor: 'transparent',
    },
    {
      id: 'zone_backend',
      type: 'rectangle',
      x: 1280,
      y: 220,
      width: 620,
      height: 180,
      strokeColor: '#1E293B',
      backgroundColor: 'rgba(15, 23, 42, 0.3)',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text_zone_backend',
      type: 'text',
      x: 1295,
      y: 230,
      width: 260,
      height: 20,
      text: 'APPLICATION CORE TIER',
      fontSize: 12,
      fontFamily: 1,
      textAlign: 'left',
      verticalAlign: 'top',
      strokeColor: '#64748B',
      backgroundColor: 'transparent',
    },
    {
      id: 'zone_storage',
      type: 'rectangle',
      x: 1930,
      y: 220,
      width: 560,
      height: 180,
      strokeColor: '#1E293B',
      backgroundColor: 'rgba(15, 23, 42, 0.3)',
      fillStyle: 'solid',
      strokeWidth: 1,
      roughness: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text_zone_storage',
      type: 'text',
      x: 1945,
      y: 230,
      width: 260,
      height: 20,
      text: 'STORAGE ENGINE TIER',
      fontSize: 12,
      fontFamily: 1,
      textAlign: 'left',
      verticalAlign: 'top',
      strokeColor: '#64748B',
      backgroundColor: 'transparent',
    },
    {
      id: 'node_browser',
      type: 'rectangle',
      x: 75,
      y: 270,
      width: 200,
      height: 80,
      strokeColor: '#00F2FE',
      backgroundColor: 'rgba(0, 242, 254, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text_browser',
      type: 'text',
      x: 80,
      y: 290,
      width: 190,
      height: 40,
      text: 'Browser Client\nOrigin (User Agent)',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#F8FAFC',
      backgroundColor: 'transparent',
    },
    {
      id: 'node_dns_resolver',
      type: 'rectangle',
      x: 360,
      y: 80,
      width: 210,
      height: 80,
      strokeColor: '#38BDF8',
      backgroundColor: 'rgba(56, 189, 248, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text_dns_resolver',
      type: 'text',
      x: 365,
      y: 100,
      width: 200,
      height: 40,
      text: 'DNS Resolver\nISP / Local (1.1.1.1)',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#F8FAFC',
      backgroundColor: 'transparent',
    },
    {
      id: 'node_dns_recursive',
      type: 'rectangle',
      x: 670,
      y: 80,
      width: 210,
      height: 80,
      strokeColor: '#38BDF8',
      backgroundColor: 'rgba(56, 189, 248, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text_dns_recursive',
      type: 'text',
      x: 675,
      y: 100,
      width: 200,
      height: 40,
      text: 'Recursive Resolver\nRoot (.) & TLD (.com)',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#F8FAFC',
      backgroundColor: 'transparent',
    },
    {
      id: 'node_dns_authoritative',
      type: 'rectangle',
      x: 980,
      y: 80,
      width: 230,
      height: 80,
      strokeColor: '#38BDF8',
      backgroundColor: 'rgba(56, 189, 248, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text_dns_authoritative',
      type: 'text',
      x: 985,
      y: 100,
      width: 220,
      height: 40,
      text: 'Authoritative DNS\nns1.example.com (A Rec)',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#F8FAFC',
      backgroundColor: 'transparent',
    },
    {
      id: 'node_reverse_proxy',
      type: 'rectangle',
      x: 360,
      y: 270,
      width: 210,
      height: 80,
      strokeColor: '#6366F1',
      backgroundColor: 'rgba(99, 102, 241, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text_reverse_proxy',
      type: 'text',
      x: 365,
      y: 290,
      width: 200,
      height: 40,
      text: 'Reverse Proxy\nTLS 1.3 Termination',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#F8FAFC',
      backgroundColor: 'transparent',
    },
    {
      id: 'node_load_balancer',
      type: 'rectangle',
      x: 670,
      y: 270,
      width: 210,
      height: 80,
      strokeColor: '#818CF8',
      backgroundColor: 'rgba(129, 140, 248, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text_load_balancer',
      type: 'text',
      x: 675,
      y: 290,
      width: 200,
      height: 40,
      text: 'Load Balancer\nRound-Robin Routing',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#F8FAFC',
      backgroundColor: 'transparent',
    },
    {
      id: 'node_api_gateway',
      type: 'rectangle',
      x: 980,
      y: 270,
      width: 220,
      height: 80,
      strokeColor: '#8B5CF6',
      backgroundColor: 'rgba(139, 92, 246, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text_api_gateway',
      type: 'text',
      x: 985,
      y: 290,
      width: 210,
      height: 40,
      text: 'API Gateway\nJWT Verify & Rate Limit',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#F8FAFC',
      backgroundColor: 'transparent',
    },
    {
      id: 'node_microservice',
      type: 'rectangle',
      x: 1310,
      y: 270,
      width: 220,
      height: 80,
      strokeColor: '#00F2FE',
      backgroundColor: 'rgba(0, 242, 254, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text_microservice',
      type: 'text',
      x: 1315,
      y: 290,
      width: 210,
      height: 40,
      text: 'Microservice\nOrder Service Instance',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#F8FAFC',
      backgroundColor: 'transparent',
    },
    {
      id: 'node_business_layer',
      type: 'rectangle',
      x: 1630,
      y: 270,
      width: 220,
      height: 80,
      strokeColor: '#F59E0B',
      backgroundColor: 'rgba(245, 158, 11, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text_business_layer',
      type: 'text',
      x: 1635,
      y: 290,
      width: 210,
      height: 40,
      text: 'Business Layer\nDomain Logic Validation',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#F8FAFC',
      backgroundColor: 'transparent',
    },
    {
      id: 'node_database',
      type: 'rectangle',
      x: 1960,
      y: 270,
      width: 220,
      height: 80,
      strokeColor: '#10B981',
      backgroundColor: 'rgba(16, 185, 129, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text_database',
      type: 'text',
      x: 1965,
      y: 290,
      width: 210,
      height: 40,
      text: 'Database (PostgreSQL)\nACID Transaction Engine',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#F8FAFC',
      backgroundColor: 'transparent',
    },
    {
      id: 'node_wal',
      type: 'rectangle',
      x: 2250,
      y: 270,
      width: 200,
      height: 80,
      strokeColor: '#EF4444',
      backgroundColor: 'rgba(239, 68, 68, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 0,
      roundness: { type: 3 },
    },
    {
      id: 'text_wal',
      type: 'text',
      x: 2255,
      y: 290,
      width: 190,
      height: 40,
      text: 'Write-Ahead Log\nWAL Fsync Durability',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#F8FAFC',
      backgroundColor: 'transparent',
    },
    {
      id: 'arrow_dns_query',
      type: 'arrow',
      x: 275,
      y: 290,
      width: 85,
      height: -170,
      points: [
        [0, 0],
        [85, -170],
      ],
      strokeColor: '#38BDF8',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'arrow_dns_recurse',
      type: 'arrow',
      x: 570,
      y: 120,
      width: 100,
      height: 0,
      points: [
        [0, 0],
        [100, 0],
      ],
      strokeColor: '#38BDF8',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'arrow_dns_auth',
      type: 'arrow',
      x: 880,
      y: 120,
      width: 100,
      height: 0,
      points: [
        [0, 0],
        [100, 0],
      ],
      strokeColor: '#38BDF8',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'arrow_dns_reply',
      type: 'arrow',
      x: 1090,
      y: 160,
      width: -815,
      height: 120,
      points: [
        [0, 0],
        [-815, 120],
      ],
      strokeColor: '#10B981',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'arrow_browser_proxy',
      type: 'arrow',
      x: 275,
      y: 310,
      width: 85,
      height: 0,
      points: [
        [0, 0],
        [85, 0],
      ],
      strokeColor: '#6366F1',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'arrow_proxy_lb',
      type: 'arrow',
      x: 570,
      y: 310,
      width: 100,
      height: 0,
      points: [
        [0, 0],
        [100, 0],
      ],
      strokeColor: '#818CF8',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'arrow_lb_gw',
      type: 'arrow',
      x: 880,
      y: 310,
      width: 100,
      height: 0,
      points: [
        [0, 0],
        [100, 0],
      ],
      strokeColor: '#8B5CF6',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'arrow_gw_svc',
      type: 'arrow',
      x: 1200,
      y: 310,
      width: 110,
      height: 0,
      points: [
        [0, 0],
        [110, 0],
      ],
      strokeColor: '#00F2FE',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'arrow_svc_biz',
      type: 'arrow',
      x: 1530,
      y: 310,
      width: 100,
      height: 0,
      points: [
        [0, 0],
        [100, 0],
      ],
      strokeColor: '#F59E0B',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'arrow_biz_db',
      type: 'arrow',
      x: 1850,
      y: 310,
      width: 110,
      height: 0,
      points: [
        [0, 0],
        [110, 0],
      ],
      strokeColor: '#10B981',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'arrow_db_wal',
      type: 'arrow',
      x: 2180,
      y: 310,
      width: 70,
      height: 0,
      points: [
        [0, 0],
        [70, 0],
      ],
      strokeColor: '#EF4444',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
  ],
  appState: {
    viewBackgroundColor: '#0B0D10',
    gridSize: 20,
    theme: 'dark',
  },
  files: {},
};

export const DEFAULT_HTTP_REQUEST_FLOW_3D_SCENE: ThreeSceneState = {
  particles: {},
  nodes: {
    node_browser: { nodeId: 'node_browser', status: 'IDLE' },
    node_dns_resolver: { nodeId: 'node_dns_resolver', status: 'LISTENING' },
    node_dns_recursive: { nodeId: 'node_dns_recursive', status: 'LISTENING' },
    node_dns_authoritative: { nodeId: 'node_dns_authoritative', status: 'LISTENING' },
    node_reverse_proxy: { nodeId: 'node_reverse_proxy', status: 'LISTENING' },
    node_load_balancer: { nodeId: 'node_load_balancer', status: 'LISTENING' },
    node_api_gateway: { nodeId: 'node_api_gateway', status: 'LISTENING' },
    node_microservice: { nodeId: 'node_microservice', status: 'IDLE' },
    node_business_layer: { nodeId: 'node_business_layer', status: 'IDLE' },
    node_database: { nodeId: 'node_database', status: 'READY' },
    node_wal: { nodeId: 'node_wal', status: 'READY' },
  },
  connections: {
    conn_dns_query: {
      connectionId: 'conn_dns_query',
      fromNodeId: 'node_browser',
      toNodeId: 'node_dns_resolver',
      color: '#38BDF8',
      lineWidth: 2,
    },
    conn_dns_recurse: {
      connectionId: 'conn_dns_recurse',
      fromNodeId: 'node_dns_resolver',
      toNodeId: 'node_dns_recursive',
      color: '#38BDF8',
      lineWidth: 2,
    },
    conn_dns_auth: {
      connectionId: 'conn_dns_auth',
      fromNodeId: 'node_dns_recursive',
      toNodeId: 'node_dns_authoritative',
      color: '#38BDF8',
      lineWidth: 2,
    },
    conn_browser_proxy: {
      connectionId: 'conn_browser_proxy',
      fromNodeId: 'node_browser',
      toNodeId: 'node_reverse_proxy',
      color: '#6366F1',
      lineWidth: 2,
    },
    conn_proxy_lb: {
      connectionId: 'conn_proxy_lb',
      fromNodeId: 'node_reverse_proxy',
      toNodeId: 'node_load_balancer',
      color: '#818CF8',
      lineWidth: 2,
    },
    conn_lb_gw: {
      connectionId: 'conn_lb_gw',
      fromNodeId: 'node_load_balancer',
      toNodeId: 'node_api_gateway',
      color: '#8B5CF6',
      lineWidth: 2,
    },
    conn_gw_svc: {
      connectionId: 'conn_gw_svc',
      fromNodeId: 'node_api_gateway',
      toNodeId: 'node_microservice',
      color: '#00F2FE',
      lineWidth: 2,
    },
    conn_svc_biz: {
      connectionId: 'conn_svc_biz',
      fromNodeId: 'node_microservice',
      toNodeId: 'node_business_layer',
      color: '#F59E0B',
      lineWidth: 2,
    },
    conn_biz_db: {
      connectionId: 'conn_biz_db',
      fromNodeId: 'node_business_layer',
      toNodeId: 'node_database',
      color: '#10B981',
      lineWidth: 2,
    },
    conn_db_wal: {
      connectionId: 'conn_db_wal',
      fromNodeId: 'node_database',
      toNodeId: 'node_wal',
      color: '#EF4444',
      lineWidth: 2,
    },
  },
};
