import { AnimationTimeline } from '../../domain/animation/animation.interface';
import { CanvasSceneData } from '../../domain/canvas/canvas-engine.interface';
import { PlaygroundPreset } from '../../domain/playground/playground.interface';

// -------------------------------------------------------------------------
// 1. HTTP Request Flow Playground
// -------------------------------------------------------------------------
const HTTP_SCENE_DATA: CanvasSceneData = {
  elements: [
    {
      id: 'node_client',
      type: 'rectangle',
      x: 80,
      y: 180,
      width: 150,
      height: 70,
      strokeColor: '#00F2FE',
      backgroundColor: 'rgba(0, 242, 254, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 1,
      roundness: { type: 3 },
    },
    {
      id: 'text_client',
      type: 'text',
      x: 85,
      y: 196,
      width: 140,
      height: 38,
      text: 'Client (Web/App)\nJWT Bearer Token',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#FFFFFF',
      backgroundColor: 'transparent',
    },
    {
      id: 'arrow_1',
      type: 'arrow',
      x: 230,
      y: 215,
      width: 100,
      height: 0,
      points: [
        [0, 0],
        [100, 0],
      ],
      strokeColor: '#4FACFE',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'node_gateway',
      type: 'rectangle',
      x: 330,
      y: 180,
      width: 160,
      height: 70,
      strokeColor: '#4FACFE',
      backgroundColor: 'rgba(79, 172, 254, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 1,
      roundness: { type: 3 },
    },
    {
      id: 'text_gateway',
      type: 'text',
      x: 335,
      y: 196,
      width: 150,
      height: 38,
      text: 'API Gateway\nReverse Proxy & Auth',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#FFFFFF',
      backgroundColor: 'transparent',
    },
    {
      id: 'arrow_2',
      type: 'arrow',
      x: 490,
      y: 215,
      width: 100,
      height: 0,
      points: [
        [0, 0],
        [100, 0],
      ],
      strokeColor: '#00F2FE',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'node_service',
      type: 'rectangle',
      x: 590,
      y: 180,
      width: 170,
      height: 70,
      strokeColor: '#00F2FE',
      backgroundColor: 'rgba(0, 242, 254, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 1,
      roundness: { type: 3 },
    },
    {
      id: 'text_service',
      type: 'text',
      x: 595,
      y: 196,
      width: 160,
      height: 38,
      text: 'Order Service\nUse Case & Domain',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#FFFFFF',
      backgroundColor: 'transparent',
    },
    {
      id: 'arrow_3',
      type: 'arrow',
      x: 760,
      y: 215,
      width: 100,
      height: 0,
      points: [
        [0, 0],
        [100, 0],
      ],
      strokeColor: '#4FACFE',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'node_database',
      type: 'rectangle',
      x: 860,
      y: 180,
      width: 150,
      height: 70,
      strokeColor: '#4FACFE',
      backgroundColor: 'rgba(79, 172, 254, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roughness: 1,
      roundness: { type: 3 },
    },
    {
      id: 'text_database',
      type: 'text',
      x: 865,
      y: 196,
      width: 140,
      height: 38,
      text: 'PostgreSQL\nIndexed Storage',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#FFFFFF',
      backgroundColor: 'transparent',
    },
  ],
  appState: { viewBackgroundColor: '#0b0d10' },
  files: {},
};

const HTTP_TIMELINE: AnimationTimeline = {
  id: 'timeline_http',
  title: 'Flujo de Petición HTTP Distribuida',
  description:
    'Simula el recorrido de una solicitud HTTP autenticada a través de un Gateway hasta la base de datos.',
  totalFrames: 4,
  defaultSpeed: 1,
  nodePositions: {
    node_client: { x: 155, y: 215 },
    node_gateway: { x: 410, y: 215 },
    node_service: { x: 675, y: 215 },
    node_database: { x: 935, y: 215 },
  },
  frames: [
    {
      frameIndex: 0,
      title: 'Paso 1: Emisión de Solicitud HTTP',
      description:
        'El cliente web genera una petición GET /api/v1/orders adjuntando el JWT en la cabecera Authorization.',
      activeNodeIds: ['node_client'],
      durationMs: 1800,
      packets: [
        {
          id: 'pkt_1',
          fromNodeId: 'node_client',
          toNodeId: 'node_gateway',
          type: 'http',
          label: 'GET /orders [JWT]',
          color: '#00F2FE',
          durationMs: 1400,
          payloadPreview: 'Bearer eyJhbGciOi...',
        },
      ],
      pulses: [{ nodeId: 'node_client', color: '#00F2FE', scale: 2.2 }],
    },
    {
      frameIndex: 1,
      title: 'Paso 2: Validación en API Gateway',
      description:
        'El API Gateway verifica la firma criptográfica del token JWT y valida límites de tasa (Rate Limiting).',
      activeNodeIds: ['node_gateway'],
      durationMs: 1800,
      packets: [
        {
          id: 'pkt_2',
          fromNodeId: 'node_gateway',
          toNodeId: 'node_service',
          type: 'http',
          label: 'Forward Validated Request',
          color: '#4FACFE',
          durationMs: 1400,
        },
      ],
      pulses: [{ nodeId: 'node_gateway', color: '#4FACFE', scale: 2.4 }],
    },
    {
      frameIndex: 2,
      title: 'Paso 3: Ejecución de Caso de Uso en Dominio',
      description:
        'El microservicio ejecuta el Use Case `GetOrderByIdQuery` aplicando reglas de negocio y políticas de aislamiento.',
      activeNodeIds: ['node_service'],
      durationMs: 1800,
      packets: [
        {
          id: 'pkt_3',
          fromNodeId: 'node_service',
          toNodeId: 'node_database',
          type: 'query',
          label: 'SELECT * FROM orders WHERE id=$1',
          color: '#00F2FE',
          durationMs: 1400,
        },
      ],
      pulses: [{ nodeId: 'node_service', color: '#00F2FE', scale: 2.3 }],
    },
    {
      frameIndex: 3,
      title: 'Paso 4: Persistencia y Retorno 200 OK',
      description:
        'PostgreSQL recupera el registro mediante índice B-Tree (1.2ms) y el servicio devuelve HTTP 200 OK con payload JSON.',
      activeNodeIds: ['node_database'],
      durationMs: 1800,
      packets: [
        {
          id: 'pkt_4',
          fromNodeId: 'node_database',
          toNodeId: 'node_client',
          type: 'ack',
          label: '200 OK JSON [{ id: 101, status: "PAID" }]',
          color: '#10B981',
          durationMs: 1600,
        },
      ],
      pulses: [{ nodeId: 'node_database', color: '#10B981', scale: 2.5 }],
    },
  ],
};

// -------------------------------------------------------------------------
// 2. Agent Loop & Tool Calling Playground
// -------------------------------------------------------------------------
const AGENT_SCENE_DATA: CanvasSceneData = {
  elements: [
    {
      id: 'agent_user',
      type: 'rectangle',
      x: 80,
      y: 190,
      width: 140,
      height: 70,
      strokeColor: '#F59E0B',
      backgroundColor: 'rgba(245, 158, 11, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roundness: { type: 3 },
    },
    {
      id: 'text_agent_user',
      type: 'text',
      x: 85,
      y: 206,
      width: 130,
      height: 38,
      text: 'User Prompt\n"Despliega v1.2"',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#FFFFFF',
      backgroundColor: 'transparent',
    },
    {
      id: 'arrow_agent_1',
      type: 'arrow',
      x: 220,
      y: 225,
      width: 110,
      height: 0,
      points: [
        [0, 0],
        [110, 0],
      ],
      strokeColor: '#F59E0B',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'agent_core',
      type: 'rectangle',
      x: 330,
      y: 190,
      width: 170,
      height: 70,
      strokeColor: '#00F2FE',
      backgroundColor: 'rgba(0, 242, 254, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roundness: { type: 3 },
    },
    {
      id: 'text_agent_core',
      type: 'text',
      x: 335,
      y: 206,
      width: 160,
      height: 38,
      text: 'Planner Agent\n(Reasoning Loop)',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#FFFFFF',
      backgroundColor: 'transparent',
    },
    {
      id: 'arrow_agent_2',
      type: 'arrow',
      x: 500,
      y: 225,
      width: 110,
      height: 0,
      points: [
        [0, 0],
        [110, 0],
      ],
      strokeColor: '#00F2FE',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'agent_mcp',
      type: 'rectangle',
      x: 610,
      y: 190,
      width: 170,
      height: 70,
      strokeColor: '#8B5CF6',
      backgroundColor: 'rgba(139, 92, 246, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roundness: { type: 3 },
    },
    {
      id: 'text_agent_mcp',
      type: 'text',
      x: 615,
      y: 206,
      width: 160,
      height: 38,
      text: 'MCP Server\nTool Calling Protocol',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#FFFFFF',
      backgroundColor: 'transparent',
    },
    {
      id: 'arrow_agent_3',
      type: 'arrow',
      x: 780,
      y: 225,
      width: 100,
      height: 0,
      points: [
        [0, 0],
        [100, 0],
      ],
      strokeColor: '#8B5CF6',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'agent_env',
      type: 'rectangle',
      x: 880,
      y: 190,
      width: 160,
      height: 70,
      strokeColor: '#10B981',
      backgroundColor: 'rgba(16, 185, 129, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roundness: { type: 3 },
    },
    {
      id: 'text_agent_env',
      type: 'text',
      x: 885,
      y: 206,
      width: 150,
      height: 38,
      text: 'Cloud / Kubernetes\nEnvironment Action',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#FFFFFF',
      backgroundColor: 'transparent',
    },
  ],
  appState: { viewBackgroundColor: '#0b0d10' },
  files: {},
};

const AGENT_TIMELINE: AnimationTimeline = {
  id: 'timeline_agent_loop',
  title: 'Agent Loop & Tool Calling (MCP)',
  description:
    'Ciclo autónomo de razonamiento, invocación de herramientas (Tool Calling) y observación del entorno.',
  totalFrames: 4,
  defaultSpeed: 1,
  nodePositions: {
    agent_user: { x: 150, y: 225 },
    agent_core: { x: 415, y: 225 },
    agent_mcp: { x: 695, y: 225 },
    agent_env: { x: 960, y: 225 },
  },
  frames: [
    {
      frameIndex: 0,
      title: 'Paso 1: Solicitud de Usuario al Agente',
      description:
        'El usuario envía una instrucción en lenguaje natural. El agente inicializa su contexto y plan de acción.',
      activeNodeIds: ['agent_user'],
      durationMs: 1800,
      packets: [
        {
          id: 'pkt_agent_1',
          fromNodeId: 'agent_user',
          toNodeId: 'agent_core',
          type: 'token',
          label: 'Prompt Tokens',
          color: '#F59E0B',
          durationMs: 1300,
        },
      ],
      pulses: [{ nodeId: 'agent_user', color: '#F59E0B', scale: 2.2 }],
    },
    {
      frameIndex: 1,
      title: 'Paso 2: Razonamiento e Invocación de Tool Calling',
      description:
        'El agente determina que requiere ejecutar una acción en el mundo exterior mediante el Model Context Protocol (MCP).',
      activeNodeIds: ['agent_core'],
      durationMs: 1800,
      packets: [
        {
          id: 'pkt_agent_2',
          fromNodeId: 'agent_core',
          toNodeId: 'agent_mcp',
          type: 'tool_call',
          label: 'callTool("deploy", { tag: "v1.2" })',
          color: '#00F2FE',
          durationMs: 1300,
        },
      ],
      pulses: [{ nodeId: 'agent_core', color: '#00F2FE', scale: 2.4 }],
    },
    {
      frameIndex: 2,
      title: 'Paso 3: Ejecución en el Entorno Real',
      description:
        'El servidor MCP despacha la mutación al cluster Kubernetes y captura el estado de despliegue.',
      activeNodeIds: ['agent_mcp'],
      durationMs: 1800,
      packets: [
        {
          id: 'pkt_agent_3',
          fromNodeId: 'agent_mcp',
          toNodeId: 'agent_env',
          type: 'stream',
          label: 'kubectl apply -f deployment.yaml',
          color: '#8B5CF6',
          durationMs: 1300,
        },
      ],
      pulses: [{ nodeId: 'agent_mcp', color: '#8B5CF6', scale: 2.3 }],
    },
    {
      frameIndex: 3,
      title: 'Paso 4: Observación y Síntesis Final',
      description:
        'El resultado retorna al agente como observación estructurada y este genera la respuesta final al usuario.',
      activeNodeIds: ['agent_env'],
      durationMs: 1800,
      packets: [
        {
          id: 'pkt_agent_4',
          fromNodeId: 'agent_env',
          toNodeId: 'agent_user',
          type: 'ack',
          label: 'Despliegue v1.2 completado ✓',
          color: '#10B981',
          durationMs: 1500,
        },
      ],
      pulses: [{ nodeId: 'agent_env', color: '#10B981', scale: 2.5 }],
    },
  ],
};

// -------------------------------------------------------------------------
// 3. RAG Pipeline Playground
// -------------------------------------------------------------------------
const RAG_SCENE_DATA: CanvasSceneData = {
  elements: [
    {
      id: 'rag_prompt',
      type: 'rectangle',
      x: 80,
      y: 190,
      width: 140,
      height: 70,
      strokeColor: '#3B82F6',
      backgroundColor: 'rgba(59, 130, 246, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roundness: { type: 3 },
    },
    {
      id: 'text_rag_prompt',
      type: 'text',
      x: 85,
      y: 206,
      width: 130,
      height: 38,
      text: 'Query Prompt\n"¿Cómo funciona RAG?"',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#FFFFFF',
      backgroundColor: 'transparent',
    },
    {
      id: 'arrow_rag_1',
      type: 'arrow',
      x: 220,
      y: 225,
      width: 110,
      height: 0,
      points: [
        [0, 0],
        [110, 0],
      ],
      strokeColor: '#3B82F6',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'rag_embed',
      type: 'rectangle',
      x: 330,
      y: 190,
      width: 170,
      height: 70,
      strokeColor: '#00F2FE',
      backgroundColor: 'rgba(0, 242, 254, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roundness: { type: 3 },
    },
    {
      id: 'text_rag_embed',
      type: 'text',
      x: 335,
      y: 206,
      width: 160,
      height: 38,
      text: 'Embedding Model\nDense Vector [1536d]',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#FFFFFF',
      backgroundColor: 'transparent',
    },
    {
      id: 'arrow_rag_2',
      type: 'arrow',
      x: 500,
      y: 225,
      width: 110,
      height: 0,
      points: [
        [0, 0],
        [110, 0],
      ],
      strokeColor: '#00F2FE',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'rag_vdb',
      type: 'rectangle',
      x: 610,
      y: 190,
      width: 170,
      height: 70,
      strokeColor: '#EC4899',
      backgroundColor: 'rgba(236, 72, 153, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roundness: { type: 3 },
    },
    {
      id: 'text_rag_vdb',
      type: 'text',
      x: 615,
      y: 206,
      width: 160,
      height: 38,
      text: 'Vector Database\nCosine Similarity (HNSW)',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#FFFFFF',
      backgroundColor: 'transparent',
    },
    {
      id: 'arrow_rag_3',
      type: 'arrow',
      x: 780,
      y: 225,
      width: 100,
      height: 0,
      points: [
        [0, 0],
        [100, 0],
      ],
      strokeColor: '#EC4899',
      strokeWidth: 2,
      backgroundColor: 'transparent',
      endArrowhead: 'arrow',
    },
    {
      id: 'rag_llm',
      type: 'rectangle',
      x: 880,
      y: 190,
      width: 170,
      height: 70,
      strokeColor: '#10B981',
      backgroundColor: 'rgba(16, 185, 129, 0.08)',
      fillStyle: 'solid',
      strokeWidth: 2,
      roundness: { type: 3 },
    },
    {
      id: 'text_rag_llm',
      type: 'text',
      x: 885,
      y: 206,
      width: 160,
      height: 38,
      text: 'LLM Generator\nAugmented Context',
      fontSize: 13,
      fontFamily: 1,
      textAlign: 'center',
      verticalAlign: 'middle',
      strokeColor: '#FFFFFF',
      backgroundColor: 'transparent',
    },
  ],
  appState: { viewBackgroundColor: '#0b0d10' },
  files: {},
};

const RAG_TIMELINE: AnimationTimeline = {
  id: 'timeline_rag',
  title: 'Pipeline RAG (Retrieval-Augmented Generation)',
  description:
    'Vectorización semántica, búsqueda por k-vecinos próximos y síntesis con contexto enriquecido.',
  totalFrames: 4,
  defaultSpeed: 1,
  nodePositions: {
    rag_prompt: { x: 150, y: 225 },
    rag_embed: { x: 415, y: 225 },
    rag_vdb: { x: 695, y: 225 },
    rag_llm: { x: 965, y: 225 },
  },
  frames: [
    {
      frameIndex: 0,
      title: 'Paso 1: Ingesta del Prompt',
      description:
        'El usuario realiza una consulta. El texto crudo se prepara para transformación vectorial.',
      activeNodeIds: ['rag_prompt'],
      durationMs: 1800,
      packets: [
        {
          id: 'pkt_rag_1',
          fromNodeId: 'rag_prompt',
          toNodeId: 'rag_embed',
          type: 'token',
          label: 'Raw Text Query',
          color: '#3B82F6',
          durationMs: 1300,
        },
      ],
      pulses: [{ nodeId: 'rag_prompt', color: '#3B82F6', scale: 2.2 }],
    },
    {
      frameIndex: 1,
      title: 'Paso 2: Generación de Embeddings',
      description:
        'El modelo de embeddings proyecta la pregunta en un hiperespacio de 1536 dimensiones.',
      activeNodeIds: ['rag_embed'],
      durationMs: 1800,
      packets: [
        {
          id: 'pkt_rag_2',
          fromNodeId: 'rag_embed',
          toNodeId: 'rag_vdb',
          type: 'embedding',
          label: 'Vector [0.021, -0.441, ...]',
          color: '#00F2FE',
          durationMs: 1300,
        },
      ],
      pulses: [{ nodeId: 'rag_embed', color: '#00F2FE', scale: 2.4 }],
    },
    {
      frameIndex: 2,
      title: 'Paso 3: Búsqueda Semántica Vectorial (HNSW)',
      description:
        'La base de datos vectorial calcula la similitud de coseno y extrae los top-3 chunks más relevantes.',
      activeNodeIds: ['rag_vdb'],
      durationMs: 1800,
      packets: [
        {
          id: 'pkt_rag_3',
          fromNodeId: 'rag_vdb',
          toNodeId: 'rag_llm',
          type: 'stream',
          label: 'Top-3 Chunks Documentales',
          color: '#EC4899',
          durationMs: 1300,
        },
      ],
      pulses: [{ nodeId: 'rag_vdb', color: '#EC4899', scale: 2.3 }],
    },
    {
      frameIndex: 3,
      title: 'Paso 4: Generación Enriquecida con Contexto',
      description:
        'El LLM recibe la pregunta combinada con los fragmentos reales recuperados, eliminando alucinaciones.',
      activeNodeIds: ['rag_llm'],
      durationMs: 1800,
      packets: [
        {
          id: 'pkt_rag_4',
          fromNodeId: 'rag_llm',
          toNodeId: 'rag_prompt',
          type: 'ack',
          label: 'Respuesta con citas y fuentes',
          color: '#10B981',
          durationMs: 1500,
        },
      ],
      pulses: [{ nodeId: 'rag_llm', color: '#10B981', scale: 2.5 }],
    },
  ],
};

// -------------------------------------------------------------------------
// Master Catalog Exports
// -------------------------------------------------------------------------
export const PLAYGROUND_PRESETS: readonly PlaygroundPreset[] = [
  {
    id: 'http_flow',
    title: 'HTTP Request & Distributed Flow',
    badge: 'System Design',
    category: 'System Design',
    summary:
      'Ruta completa de una petición web: Client -> API Gateway -> Domain Service -> PostgreSQL.',
    sceneData: HTTP_SCENE_DATA,
    timeline: HTTP_TIMELINE,
    learningPoints: [
      'Validación de JWT en el Gateway para proteger microservicios internos.',
      'Aislamiento de la lógica de dominio en Use Cases sin acoplamiento a HTTP.',
      'Persistencia eficiente con índices B-Tree en bases de datos relacionales.',
    ],
    codeExample: {
      language: 'typescript',
      filename: 'get-order.use-case.ts',
      code: `export class GetOrderUseCase {\n  constructor(private orderRepo: OrderRepositoryPort) {}\n\n  async execute(orderId: string): Promise<OrderDTO> {\n    const order = await this.orderRepo.findById(orderId);\n    if (!order) throw new OrderNotFoundError(orderId);\n    return OrderMapper.toDTO(order);\n  }\n}`,
    },
  },
  {
    id: 'agent_loop',
    title: 'Agent Loop & Tool Calling (MCP)',
    badge: 'AI & Agents',
    category: 'AI & Agents',
    summary:
      'Ciclo de agentes autónomos: Percepción -> Razonamiento -> Invocación de herramientas (MCP) -> Síntesis.',
    sceneData: AGENT_SCENE_DATA,
    timeline: AGENT_TIMELINE,
    learningPoints: [
      'Descomposición de tareas complejas en planes ejecutables con LLMs.',
      'Invocación segura de herramientas mediante contratos formales (MCP).',
      'Integración de observaciones del entorno en la ventana de contexto.',
    ],
    codeExample: {
      language: 'typescript',
      filename: 'mcp-tool-definition.ts',
      code: `export const deployTool = {\n  name: 'deploy_service',\n  description: 'Triggers canary deployment in production cluster',\n  parameters: z.object({\n    version: z.string(),\n    weightPct: z.number().min(0).max(100),\n  }),\n};`,
    },
  },
  {
    id: 'rag_pipeline',
    title: 'Pipeline RAG & Vector Search',
    badge: 'AI & Embeddings',
    category: 'AI & Agents',
    summary:
      'Generación Aumentada por Recuperación: embeddings, cálculo de similitud de coseno y contexto enriquecido.',
    sceneData: RAG_SCENE_DATA,
    timeline: RAG_TIMELINE,
    learningPoints: [
      'Conversión de texto a vectores densos mediante modelos de embeddings.',
      'Búsqueda eficiente en grafos de alta dimensión con índices HNSW.',
      'Mitigación de alucinaciones inyectando conocimiento fáctico en el prompt.',
    ],
    codeExample: {
      language: 'typescript',
      filename: 'cosine-search.ts',
      code: `export async function vectorSearch(queryVector: number[], topK = 3) {\n  return vectorDb.query({\n    vector: queryVector,\n    topK,\n    includeMetadata: true,\n  });\n}`,
    },
  },
];
